services: 
  db: 
    image: postgres:16
    container_name: pg-practica-libros 
    restart: unless-stopped 
    environment: 
      POSTGRES_USER: ADMIN 
      POSTGRES_PASSWORD: ADMIN
      POSTGRES_DB: baseDatosLibrosEduardo 
    ports: 
      - "5432:5432" 
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
volumes: 
  pgdata: 